### ISSUE TITLE
The '--fix' command replaces all of them with 'NameSpace' by the 'use-name-space-import' rule.

### ISSUE THREAD

**Issue by suzu2469** [hrbrain/eslint-plugin#18]
from:
<img width="524" alt="スクリーンショット 2020-07-30 17 00 36" src="https://user-images.githubusercontent.com/20917740/88897438-38494d00-d286-11ea-848f-a6c1ced67983.png">

to:
<img width="492" alt="スクリーンショット 2020-07-30 17 00 25" src="https://user-images.githubusercontent.com/20917740/88897459-44350f00-d286-11ea-8695-1d6c434aafb3.png">

It is very inconvenient for all names to be set to 'NameSpace', so please don't replace them when we use the '--write' option.

**Comment by hrb-yamamoto-katsuya** [comment]
OK.
We need remove fixable option from this rule.

**Comment by hrb-yamamoto-katsuya** [comment]
@suzu2469 
Thank for the issue.
This proposal will release as v0.2.0.
